import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {encodeTorque,exactWithinCap,verifyManifest,check} from '../scripts/review-actuation74.mjs';
test('physical POST-H has independent matrix, shifted-origin and quaternion-sign checks',()=>{const r=check();assert.equal(r.states,28);assert.ok(r.matrix_H_max_error<1e-14);assert.ok(r.origin_shift_max_error<1e-14);assert.equal(r.quaternion_sign_max_error,0);assert.ok(r.reversed_frame_tensor_negative_separation>1e-5);});
test('representation cap is strict and not a per-axis box or residual tolerance',()=>{assert.equal(exactWithinCap([Math.fround(.15),0,0],.15),false);assert.throws(()=>encodeTorque([.15,.15,0]));assert.throws(()=>encodeTorque([Infinity,0,0]));for(const v of [[.15,0,0],[-.15,0,0],[.08,.04,.09]]){const q=encodeTorque(v);assert.ok(exactWithinCap(q,.15));assert.ok(q.every((x,i)=>Math.abs(x)<=Math.abs(v[i])));assert.ok(q.every(x=>Math.fround(x)===x));}});
test('manifest rejects mismatched expected hash',()=>{const dir='docs/research/standing-lab/gate-b72',m=JSON.parse(fs.readFileSync(dir+'/sha256.json'));m['README.md']='0'.repeat(64);assert.throws(()=>verifyManifest(dir,m));});

test('manifest rejects omitted and unexpected entries; legacy exclusions are explicit',()=>{const dir='docs/research/standing-lab/gate-b72',m=JSON.parse(fs.readFileSync(dir+'/sha256.json'));assert.equal(verifyManifest(dir,m),12);const missing={...m};delete missing['README.md'];assert.throws(()=>verifyManifest(dir,missing));assert.throws(()=>verifyManifest(dir,{}));assert.throws(()=>verifyManifest(dir,{...m,'../README.md':'0'.repeat(64)}));const legacy='docs/research/standing-lab/torso-torque60';assert.throws(()=>verifyManifest(legacy));assert.equal(verifyManifest(legacy,undefined,['README.md']),5);});
