import {test} from 'node:test';import assert from 'node:assert/strict';import R from '@dimforge/rapier3d-compat';import {Quaternion,Vector3,Euler} from 'three';
import {fallenCase} from './getup-fixture.js';import {captureSupports,supportPose,checkedSupportMove} from '../src/support-path.js';import {FourSupportRise} from '../src/four-support-rise.js';import {SideSupportProbe} from '../src/side-support-probe.js';import {observeGetup} from '../src/getup-observation.js';import {ContactGrab} from '../src/grab.js';
await R.init();const dt=1/60;
test('common pose checks all four chains with extension reserve and ankle constraints, without moving bodies',()=>{
 const f=fallenCase(R,-1);try{const c=new FourSupportRise(R,f.world,f.rig,f.floor),before=[...f.rig.byId.values()].map(({body})=>({...body.translation()}));
  assert.ok(c.preflight.every(p=>p.feasible));const p=c.preflight.at(-1);assert.ok(p.headClearance>.5);
  for(const limb of Object.values(p.limbs))assert.ok(limb.reach<=limb.maxReach);
  const q=new Quaternion().setFromAxisAngle(new Vector3(0,1,0),.7),rot=v=>new Vector3(v.x,v.y,v.z).applyQuaternion(q),supports=structuredClone(c.supports),pose=structuredClone(p.pose);
  for(const side of ['L','R']){supports.hands[side]=rot(supports.hands[side]);supports.feet[side].ankle=rot(supports.feet[side].ankle);supports.feet[side].rotation=q.clone().multiply(new Quaternion().copy(supports.feet[side].rotation));}
  // Pure yaw covariance for a pose with no root roll/yaw.
  pose.yaw=0;pose.roll=0;const original=supportPose(f.rig,c.supports,pose);pose.position=rot(pose.position);const rootQ=q.clone().multiply(new Quaternion().setFromAxisAngle(new Vector3(1,0,0),pose.pitch));
  const e=new Euler().setFromQuaternion(rootQ,'XYZ');Object.assign(pose,{pitch:e.x,yaw:e.y,roll:e.z});
  const rotated=supportPose(f.rig,supports,pose);assert.equal(rotated.feasible,original.feasible);for(const id of Object.keys(original.limbs))assert.ok(Math.abs(rotated.limbs[id].reach-original.limbs[id].reach)<1e-8);
  const extended=structuredClone(c.supports);extended.hands.L.x+=.3;const tooFar=supportPose(f.rig,extended,p.pose);assert.equal(tooFar.feasible,false);assert.ok(tooFar.reasons.includes('arm-L'));
  assert.equal(checkedSupportMove(f.rig,extended,p.pose,p.pose).feasible,false);
  const nonfinite=structuredClone(p.pose);nonfinite.position.y=Infinity;assert.equal(checkedSupportMove(f.rig,c.supports,p.pose,nonfinite).feasible,false);
  assert.deepEqual([...f.rig.byId.values()].map(({body})=>({...body.translation()})),before);
  const broken=structuredClone(c.supports);broken.feet.R.rotation=new Quaternion().setFromAxisAngle(new Vector3(1,0,0),1.5);
  const rejected=supportPose(f.rig,broken,p.pose);assert.equal(rejected.feasible,false);assert.ok(rejected.reasons.includes('leg-R'));
  c.stop('teardown');
 }finally{f.world.free();}
});

test('singular leg plane is rejected rather than returning an actionable NaN motor',()=>{const f=fallenCase(R,-1);try{const c=new FourSupportRise(R,f.world,f.rig,f.floor),pose=c.path[0],supports=captureSupports(f.rig);const hip=f.rig.joints.get('hipL').spec.anchorA;const offset=new Vector3(hip.x,hip.y,hip.z).applyQuaternion(new Quaternion().setFromEuler(new Euler(pose.pitch,pose.yaw,pose.roll)));supports.feet.L.ankle={x:pose.position.x+offset.x,y:pose.position.y+offset.y,z:pose.position.z+offset.z};const p=supportPose(f.rig,supports,pose);assert.equal(p.feasible,false);assert.ok(p.reasons.includes('degenerate-leg-L'));c.stop('teardown');}finally{f.world.free();}});
test('real four-support trial detects slip while COM remains inside support: no head-free dwell or foot lift',()=>{const f=fallenCase(R,-1);let c;try{c=new FourSupportRise(R,f.world,f.rig,f.floor);const fixed=structuredClone(c.supports);let stands=0;for(let i=0;i<180&&!c.disposed;i++){for(const {body} of f.rig.byId.values())body.resetTorques(false);c.step(dt);f.world.step();stands+=Number(observeGetup(f.world,f.rig,f.floor).standing);if(c.planning){assert.ok(c.planning.feasible);assert.equal(c.planning.motors.neck,.4);}}assert.equal(c.phase,'hand-support-slip');assert.ok(c.elapsed<2);assert.equal(c.dwell,0);assert.equal(stands,0);assert.equal(c.footStep,undefined);assert.deepEqual(c.supports,fixed);assert.ok(c.feedback.head>5&&c.feedback.margin>0);assert.ok(Object.values(c.feedback.supportSlip).some(d=>d>.05));for(const {body} of f.rig.byId.values()){assert.equal(body.additionalSolverIterations(),0);assert.deepEqual({...body.userTorque()},{x:0,y:0,z:0});}}finally{c?.stop('teardown');f.world.free();}});
test('belly fixture rejects the back-specific common path before applying motors',()=>{const f=fallenCase(R,1);try{const c=new FourSupportRise(R,f.world,f.rig,f.floor);assert.equal(c.phase,'no-common-path');assert.equal(c.elapsed,0);for(const {body} of f.rig.byId.values())assert.equal(body.additionalSolverIterations(),0);}finally{f.world.free();}});
test('alternative roll changes real orientation but does not label a head/leg-supported collapse as success',()=>{for(const direction of [-1,1]){const f=fallenCase(R,direction);let c;try{c=new SideSupportProbe(R,f.world,f.rig,f.floor);for(let i=0;i<200&&!c.disposed;i++){for(const {body} of f.rig.byId.values())body.resetTorques(false);c.step(dt);f.world.step();if(c.feedback)assert.ok(Math.abs(c.feedback.torque??0)<=24);}assert.equal(c.phase,'side-probe-timeout');assert.equal(c.dwell,0);assert.ok(c.feedback.forward.x>.5);assert.equal(observeGetup(f.world,f.rig,f.floor).standing,false);assert.ok(c.feedback.contacts.some(p=>p.id.startsWith('upperLeg')&&p.force>20));assert.equal(f.world.bodies.len(),15);assert.equal(f.world.impulseJoints.len(),14);for(const {body} of f.rig.byId.values())assert.equal(body.additionalSolverIterations(),0);}finally{c?.stop('teardown');f.world.free();}}});
test('new probes freeze feedback/planning during pause and restore frames/budget before G2 ownership',()=>{for(const Controller of [FourSupportRise,SideSupportProbe]){const f=fallenCase(R,-1);let c;try{const hand=f.rig.byId.get('handL').body;hand.setAdditionalSolverIterations(3);const frames=new Map([...f.rig.joints].map(([id,{joint}])=>[id,{...joint.frameX1()}]));c=new Controller(R,f.world,f.rig,f.floor);c.step(dt);const time=c.elapsed,progress=c.progress,bias=structuredClone(c.bias);c.step(dt,{paused:true});c.step(1,{paused:true});assert.equal(c.elapsed,time);assert.equal(c.progress,progress);assert.deepEqual(c.bias,bias);assert.equal(hand.additionalSolverIterations(),3);c.step(dt);assert.equal(hand.additionalSolverIterations(),19);c.step(dt,{held:true});assert.ok(c.disposed);for(const [id,{joint}] of f.rig.joints)assert.deepEqual({...joint.frameX1()},frames.get(id));assert.equal(hand.additionalSolverIterations(),3);const grab=new ContactGrab(f.world,R);grab.begin(hand,hand.translation(),0,9.06);assert.equal(hand.additionalSolverIterations(),7);grab.cancel('reset');assert.equal(hand.additionalSolverIterations(),3);assert.equal(f.world.bodies.len(),15);assert.equal(f.world.impulseJoints.len(),14);}finally{c?.stop('teardown');f.world.free();}}});
