// Recompute from stored raw observations; no Rapier import/world steps.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import {PROTOCOL_HEAD,CONFIG_SHA,PROTOCOL_SHA,commandAudit,metrics,discriminate,oracleControls,publicControls} from './actuation75-model.mjs';
export function validateActuation(r,cfg){
 const keys=(o,n)=>assert.deepEqual(Object.keys(o).sort(),n.split(',').sort());keys(r,'schema_version,study,provenance,case_count,fresh_worlds,oracle_controls,cases,command_contract,independent_controls,local_discrimination,engine_precision,bounded_actuation_evidence');
 const forbidden=x=>{if(x&&typeof x==='object')for(const [k,v]of Object.entries(x)){assert.ok(!/^(pass_physics|physics_pass|accepted_physics|controller_approved|standing_approved|gate_b_approved|upright_approved)$/.test(k),'unscoped physics/standing approval field');forbidden(v);}};forbidden(r);
 const finite=x=>{if(typeof x==='number')assert.ok(Number.isFinite(x));else if(x&&typeof x==='object')Object.values(x).forEach(finite);};finite(r);assert.equal(r.schema_version,1);assert.equal(r.study,'bounded-actuation75-v1');assert.equal(r.fresh_worlds,135);assert.equal(r.case_count,27);assert.equal(r.provenance.dirty,false);assert.match(r.provenance.git_commit,/^[a-f0-9]{40}$/);assert.match(r.provenance.build_id,new RegExp('^'+r.provenance.git_commit+':[a-f0-9]{64}$'));assert.equal(r.provenance.protocol_head,PROTOCOL_HEAD);assert.equal(r.provenance.config_sha256,CONFIG_SHA);assert.equal(r.provenance.protocol_sha256,PROTOCOL_SHA);assert.equal(r.provenance.rapier,'0.21.0');assert.equal(r.provenance.upstream,cfg.upstream);assert.equal(r.provenance.node,'v24.21.0');assert.deepEqual(r.cases.map(x=>x.id),cfg.cases.map(x=>x.id));
 const historical=JSON.parse(fs.readFileSync('docs/research/standing-lab/torso-torque60/gate-b.json')),capsules=JSON.parse(fs.readFileSync('docs/research/standing-lab/gate-b72/attribution.json')).cases[0].runs[0].pre;const cache=new Map(),seeds=new Map();let positive=0,negative=0,impulses=0;
 for(const [i,ca]of r.cases.entries()){const c=cfg.cases[i];keys(ca,'id,runs');assert.equal(ca.runs.length,5);for(const [j,x]of ca.runs.entries()){
 keys(x,'id,repeat,T,pre,post,commands,phase,after_reset,accumulators,cleared,forces_before,forces_after,public_steps,counts,environment,public_inverse_tensors,public_controls,oracle_control_key,termination,command_audit,metrics');
 assert.equal(x.id,c.id+'/'+(j+1));assert.equal(x.repeat,j+1);assert.equal(x.T,Math.fround(1/60));assert.equal(x.termination,'completed_bounded_measurement');assert.deepEqual(x.pre,c.synthetic?historical.first_steps.find(x=>x.synthetic&&x.method==='impulse').pre:capsules);assert.deepEqual(x.counts,{bodies:2,colliders:c.synthetic?0:2,joints:c.connected?1:0});
 for(const b of [...x.pre,...x.post]){assert.ok(b.mass>0&&Object.values(b.inertia).every(v=>v>0));}assert.deepEqual(x.post.map(b=>[b.id,b.mass,b.anchor,b.inertia,b.principal_frame]),x.pre.map(b=>[b.id,b.mass,b.anchor,b.inertia,b.principal_frame]));
 assert.deepEqual(x.environment.gravity,{x:0,y:0,z:0});const ip=x.environment.integration;assert.equal(ip.dt,x.T);assert.equal(ip.numSolverIterations,32);assert.equal(ip.numInternalPgsIterations,1);assert.equal(ip.maxCcdSubsteps,1);assert.equal(x.environment.bodies.length,2);assert.ok(x.environment.bodies.every(b=>b.dynamic&&!b.sleeping&&b.linear_damping===0&&b.angular_damping===0&&b.additional_solver_iterations===0&&!b.ccd));assert.equal(x.environment.joint_contacts_enabled,c.connected?false:null);
 assert.deepEqual(x.command_audit,commandAudit(c,x));assert.deepEqual(x.public_controls,publicControls(x.pre,x.public_inverse_tensors,c.synthetic));assert.equal(x.public_controls.pass,true);assert.equal(x.oracle_control_key,JSON.stringify(x.pre));seeds.set(x.oracle_control_key,x.pre);
 assert.deepEqual(x.metrics,metrics(c,x,cfg,cache));
 for(let b=0;b<2;b++)assert.deepEqual(x.phase[2+b].readback_angular_velocity,c.method==='impulse'?x.post[b].angular_velocity:x.pre[b].angular_velocity);
 if(c.method==='impulse'){impulses++;assert.ok(x.metrics.endpoint_error.angular<=1e-5&&x.metrics.endpoint_error.linear<=1e-5);assert.deepEqual(x.post.map(b=>[b.rotation,b.world_com,b.linear_velocity]),x.pre.map(b=>[b.rotation,b.world_com,b.linear_velocity]));}
 if(c.fault)negative++;else positive++;
 if(j){const canonical=y=>({...y,id:c.id+'/1',repeat:1});assert.deepEqual(canonical(x),canonical(ca.runs[0]));}
 }}
 assert.equal(r.oracle_controls.length,seeds.size);assert.deepEqual(r.oracle_controls.map(x=>x.key),[...seeds.keys()]);for(const x of r.oracle_controls)assert.deepEqual(x.result,oracleControls(seeds.get(x.key),Math.fround(1/60)));
 const local=discriminate(r.cases);assert.deepEqual(r.local_discrimination,local);assert.equal(r.command_contract,'positive_commands_pass_expected_negative_violations_observed');assert.equal(r.independent_controls,'pass');assert.deepEqual(r.engine_precision,{status:'indeterminate_not_certified',general_envelope:null,endpoint_acceptance_marker:null,H_acceptance_marker:null});assert.equal(r.bounded_actuation_evidence,local.pass?'local_supported':'actuation_discrimination_blocked');return {valid:true,fresh_worlds:135,positive_observations:positive,negative_observations:negative,immediate_impulse_controls:impulses,local_discrimination:local,bounded_actuation_evidence:r.bounded_actuation_evidence,engine_precision:'indeterminate_not_certified',upright_approval:false};
}
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){const p='docs/research/standing-lab/actuation74/',hash=b=>createHash('sha256').update(b).digest('hex'),raw=fs.readFileSync(p+'config.json');assert.equal(hash(raw),CONFIG_SHA);assert.equal(hash(fs.readFileSync(p+'protocol.md')),PROTOCOL_SHA);console.log(JSON.stringify(validateActuation(JSON.parse(fs.readFileSync(process.argv[2])),JSON.parse(raw))));}
