// Independent stored-only reader. No engine or runner/model import.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import Ajv from 'ajv';
const resultValidator=new Ajv({strict:true,allErrors:true}).compile(JSON.parse(fs.readFileSync(new URL('../docs/research/standing-lab/fullrig84/result.schema.json',import.meta.url))));
import {createHash} from 'node:crypto';
const plan=JSON.parse(fs.readFileSync(new URL('../docs/research/standing-lab/fullrig83/plan.json',import.meta.url))),rig=JSON.parse(fs.readFileSync(new URL('../docs/research/standing-lab/baseline-config.json',import.meta.url)));
const V=o=>[o.x,o.y,o.z],N=a=>Math.hypot(...a),D=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),S=(a,k)=>a.map(x=>x*k),A=(a,b)=>a.map((x,i)=>x+b[i]),B=(a,b)=>a.map((x,i)=>x-b[i]),X=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const keys=(o,ks)=>assert.deepEqual(Object.keys(o).sort(),ks.split(',').sort(),'field set');
const close=(a,b,t=1e-12)=>assert.ok(Math.abs(a-b)<=t, 'numeric redundancy '+a+' vs '+b);
function finite(o){if(typeof o==='number')assert.ok(Number.isFinite(o));else if(o&&typeof o==='object')Object.values(o).forEach(finite);}
function matrix(q){const n=Math.hypot(q.x,q.y,q.z,q.w);assert.ok(n>0);const x=q.x/n,y=q.y/n,z=q.z/n,w=q.w/n;return [[1-2*(y*y+z*z),2*(x*y-z*w),2*(x*z+y*w)],[2*(x*y+z*w),1-2*(x*x+z*z),2*(y*z-x*w)],[2*(x*z-y*w),2*(y*z+x*w),1-2*(x*x+y*y)]];}
const mv=(m,v)=>m.map(r=>D(r,v)),mm=(a,b)=>a.map(r=>b[0].map((_,j)=>D(r,b.map(r=>r[j]))));
const cp=q=>({x:-q.x,y:-q.y,z:-q.z,w:q.w});
function qm(a,b){return {w:a.w*b.w-D(V(a),V(b)),...Object.fromEntries(['x','y','z'].map((k,i)=>[k,a.w*V(b)[i]+b.w*V(a)[i]+X(V(a),V(b))[i]]))};}
function qdist(a,b){const an=Math.hypot(...Object.values(a)),bn=Math.hypot(...Object.values(b)),sign=D([a.x,a.y,a.z,a.w],[b.x,b.y,b.z,b.w])<0?-1:1;return 4*Math.asin(Math.min(1,N([a.x/an-sign*b.x/bn,a.y/an-sign*b.y/bn,a.z/an-sign*b.z/bn,a.w/an-sign*b.w/bn])/2));}
function dyadic(x){const d=new DataView(new ArrayBuffer(8));d.setFloat64(0,Math.abs(x));const u=d.getBigUint64(0),e=Number((u>>52n)&2047n),f=u&((1n<<52n)-1n);return e?((1n<<52n)|f)<<BigInt(e-1):f;}
function within(a,c){const d=dyadic(c);return a.map(dyadic).reduce((s,x)=>s+x*x,0n)<=d*d;}
function scalar(x){if(x===0)return 0;const a=Math.abs(x);let f=Math.fround(a);if(f>a){const t=new Float32Array([f]),u=new Uint32Array(t.buffer);u[0]--;f=t[0];}return Math.sign(x)*f;}
export function independentLaw(body,fault=null){const u=mv(matrix(body.rotation),[0,1,0]),c=[-u[2],0,u[0]],sn=N(c),theta=Math.atan2(sn,u[1]),e=sn?S(c,theta/sn):[0,0,0],w=V(body.angular_velocity),wp=B(w,S(u,D(u,w))),raw=B(S(e,plan.controller.kp_Nm_per_rad*(fault==='wrong-sign'?-1:1)),S(wp,plan.controller.kd_Nm_s_per_rad)),n=N(raw),C=plan.controller.cap_Nm;let bounded=n>C?S(raw,C/n):raw.slice();while(!within(bounded,C))bounded=bounded.map(x=>x*(1-Number.EPSILON));const encoded=bounded.map(scalar);return {up:u,theta,error:e,wperp:wp,raw,bounded,encoded,pelvis:fault==='missing-reaction'?[0,0,0]:encoded.map(x=>x===0?0:-x),cap_ratio:n/C,encoding_delta:B(encoded,bounded),encoded_axial:D(encoded,u)};}
export function derived(state,initial){
 const bodies=state.bodies,by=new Map(bodies.map(b=>[b.id,b])),mass=bodies.reduce((s,b)=>s+b.mass,0),com=S(bodies.reduce((s,b)=>A(s,S(V(b.world_com),b.mass)),[0,0,0]),1/mass);let H=[0,0,0],KE=0,PE=0;
 for(const b of bodies){const Q=mm(matrix(b.rotation),matrix(b.principal_frame)),w=V(b.angular_velocity),vl=V(b.linear_velocity),local=Q[0].map((_,i)=>D(Q.map(r=>r[i]),w)),Iw=mv(Q,local.map((x,i)=>x*V(b.inertia)[i]));H=A(H,A(Iw,X(V(b.world_com),S(vl,b.mass))));KE+=.5*b.mass*D(vl,vl)+.5*D(w,Iw);PE+=b.mass*9.81*b.world_com.y;}
 const torso=by.get('torso'),torsoLaw=independentLaw(torso),forward=mv(matrix(torso.rotation),[0,0,1]),yaw=Math.atan2(forward[0],forward[2]),pf=mv(matrix(by.get('pelvis').rotation),[0,0,1]),pelvis_yaw=Math.atan2(pf[0],pf[2]),loads={footL:state.step===0?null:0,footR:state.step===0?null:0};
 for(const c of state.floor_contacts){keys(c,'body_id,collider_id,point,normal,distance,normal_impulse,normal_load');assert.ok(c.distance<=0);assert.ok(by.has(c.body_id));assert.equal(c.collider_id,'collider:'+c.body_id);if(state.step>0){assert.ok(c.normal_impulse>=0);close(c.normal_load,c.normal_impulse/state.settings.dt*c.normal.y,1e-10);if(c.body_id in loads)loads[c.body_id]+=c.normal_load;}else{assert.equal(c.normal_impulse,null);assert.equal(c.normal_load,null);}}
 const nonfoot=[...new Set(state.floor_contacts.filter(c=>!['footL','footR'].includes(c.body_id)).map(c=>c.body_id))].sort();
 const foot_drift={};for(const id of ['footL','footR']){const a=by.get(id).world_com,b=(initial??state).bodies.find(b=>b.id===id).world_com;foot_drift[id]=Math.hypot(a.x-b.x,a.z-b.z);}
 const origin=initial?derived(initial,null):{com,yaw};
 return {mass,com,tilt:torsoLaw.theta,transverse_speed:N(torsoLaw.wperp),yaw,pelvis_yaw,yaw_drift:Math.abs(Math.atan2(Math.sin(yaw-origin.yaw),Math.cos(yaw-origin.yaw))),com_drift:Math.hypot(com[0]-origin.com[0],com[2]-origin.com[2]),foot_drift,loads,nonfoot,foot_contact:state.floor_contacts.some(c=>c.body_id==='footL'||c.body_id==='footR'),H,KE,PE};
}
function validateState(s){
 if(s.step>0){const rebuilt=[];for(const m of s.floor_manifolds){keys(m,'body_id,flipped,normal,contacts');assert.equal(typeof m.flipped,'boolean');const body=s.bodies.find(b=>b.id===m.body_id);assert.ok(body);for(const c of m.contacts){keys(c,'distance,local1,local2,impulse');assert.ok(c.impulse>=0);if(c.distance>0)continue;const local=m.flipped?c.local1:c.local2,point=A(V(body.collider_position),mv(matrix(body.collider_rotation),V(local))),normal=S(V(m.normal),m.flipped?-1:1);rebuilt.push({body_id:m.body_id,collider_id:'collider:'+m.body_id,point:{x:point[0],y:point[1],z:point[2]},normal:{x:normal[0],y:normal[1],z:normal[2]},distance:c.distance,normal_impulse:c.impulse,normal_load:c.impulse/s.settings.dt*normal[1]});}}rebuilt.sort((a,b)=>a.body_id.localeCompare(b.body_id)||a.point.x-b.point.x||a.point.y-b.point.y||a.point.z-b.point.z);assert.equal(rebuilt.length,s.floor_contacts.length,'all actual manifold contacts retained');for(let i=0;i<rebuilt.length;i++){const a=rebuilt[i],b=s.floor_contacts[i];assert.equal(a.body_id,b.body_id);assert.equal(a.distance,b.distance);assert.equal(a.normal_impulse,b.normal_impulse);close(a.normal_load,b.normal_load,1e-10);V(a.point).forEach((x,j)=>close(x,V(b.point)[j],1e-6));assert.deepEqual(a.normal,b.normal);}}

 keys(s,'step,observed_time,settings,bodies,joints,floor_contacts,self_contacts,floor_manifolds,motor_tracking,native_effort,native_effort_reason,cpu_ms');finite(s);close(s.observed_time,s.step*plan.nominal_dt,1e-12);assert.ok(Number.isInteger(s.step)&&s.step>=0);assert.equal(s.native_effort,null);assert.equal(s.bodies.length,15);assert.deepEqual(s.bodies.map(b=>b.id),rig.bodies.map(b=>b.id));assert.equal(s.joints.length,14);assert.deepEqual(s.joints.map(j=>j.id),rig.joints.map(j=>j.id));keys(s.settings,'floor,dt,gravity,solver,counts,motor_config');const floor=s.settings.floor;keys(floor,'parent,native_shape_type,position,rotation,half,friction,restitution,friction_combine,restitution_combine,contact_skin,sensor,collision_groups');assert.equal(floor.parent,null);assert.equal(floor.native_shape_type,1);assert.deepEqual(V(floor.position),V(rig.floor.position).map(Math.fround));assert.deepEqual(V(floor.half),V(rig.floor.half).map(Math.fround));assert.deepEqual(floor.rotation,{x:0,y:0,z:0,w:1});assert.equal(floor.friction,Math.fround(rig.floor.friction));assert.equal(floor.restitution,Math.fround(rig.floor.restitution));assert.equal(floor.friction_combine,0);assert.equal(floor.restitution_combine,0);assert.equal(floor.contact_skin,0);assert.equal(floor.sensor,false);assert.equal(floor.collision_groups,4294967295);assert.equal(s.settings.dt,plan.observed_dt);assert.deepEqual(s.settings.gravity,rig.gravity);assert.deepEqual(s.settings.counts,{bodies:15,colliders:16,joints:14});for(const [k,x]of Object.entries(plan.solver))if(k!=='additionalSolverIterations')assert.equal(s.settings.solver[k],Math.fround(x));
 for(const b of s.bodies){keys(b,'id,body_handle,collider_handle,position,rotation,linear_velocity,angular_velocity,mass,world_com,inertia,principal_frame,world_inverse_inertia,sleeping,dynamic,ccd,additional_solver_iterations,linear_damping,angular_damping,user_torque,user_force,collider_position,collider_rotation,friction,restitution,sensor,native_shape_type,observed_shape,friction_combine,restitution_combine,contact_skin,collision_groups,shape');for(const k of ['position','world_com','linear_velocity','angular_velocity','inertia','user_torque','user_force','collider_position'])keys(b[k],'x,y,z');for(const k of ['rotation','principal_frame','collider_rotation']){keys(b[k],'x,y,z,w');assert.ok(Math.abs(Math.hypot(...Object.values(b[k]))-1)<1e-4);}assert.ok(V(b.inertia).every(x=>x>0));assert.equal(b.world_inverse_inertia.length,6);assert.equal(b.dynamic,true);assert.equal(b.ccd,false);assert.equal(b.additional_solver_iterations,0);const spec=rig.bodies.find(x=>x.id===b.id);close(b.mass,spec.mass,1e-5);assert.equal(b.linear_damping,Math.fround(spec.linearDamping));assert.equal(b.angular_damping,Math.fround(spec.angularDamping));assert.equal(b.friction,Math.fround(spec.friction));assert.equal(b.restitution,Math.fround(spec.restitution));assert.equal(b.sensor,false);assert.deepEqual(b.shape,spec.shape);const quant=x=>typeof x==='number'?Math.fround(x):x&&typeof x==='object'?Object.fromEntries(Object.entries(x).map(([k,v])=>[k,quant(v)])):x;assert.deepEqual(b.observed_shape,quant(spec.shape));assert.equal(b.native_shape_type,{ball:0,cuboid:1,capsule:2}[spec.shape.type]);assert.equal(b.friction_combine,0);assert.equal(b.restitution_combine,0);assert.equal(b.contact_skin,0);assert.equal(b.collision_groups,4294967295);assert.deepEqual(V(b.user_force),[0,0,0]);}
 for(const j of s.joints){keys(j,'id,parent,child,kind,handle,native_type,anchor1,anchor2,frame1,frame2,contacts_enabled,limits,observation');const spec=rig.joints.find(x=>x.id===j.id);assert.equal(j.parent,spec.parent);assert.equal(j.child,spec.child);assert.equal(j.kind,spec.type);assert.equal(j.contacts_enabled,false);assert.deepEqual(j.limits,spec.limits?.map(Math.fround)??null);assert.deepEqual(V(j.anchor1),V(spec.anchorA).map(Math.fround));assert.deepEqual(V(j.anchor2),V(spec.anchorB).map(Math.fround));const a=s.bodies.find(b=>b.id===j.parent),b=s.bodies.find(b=>b.id===j.child),pa=A(V(a.position),mv(matrix(a.rotation),V(j.anchor1))),pb=A(V(b.position),mv(matrix(b.rotation),V(j.anchor2)));close(j.observation.anchor_error,N(B(pa,pb)),1e-6);if(j.kind==='revolute'){const rel=qm(cp(qm(a.rotation,j.frame1)),qm(b.rotation,j.frame2)),angle=Math.atan2(Math.sin(2*Math.atan2(rel.x,rel.w)),Math.cos(2*Math.atan2(rel.x,rel.w)));close(j.observation.angle,angle,1e-6);close(j.observation.limit_violation,Math.max(0,j.limits[0]-angle,angle-j.limits[1]),1e-6);}}
}
export function stateStop(s,initial){const d=derived(s,initial);for(const b of s.bodies){if(N(V(b.angular_velocity))>plan.limits.segment_speed_rad_s[b.id])return 'segment_speed:'+b.id;if(N(V(b.position))>20||N(V(b.linear_velocity))>50||N(V(b.angular_velocity))>200)return 'outer_state:'+b.id;}for(const j of s.joints){const a=s.bodies.find(b=>b.id===j.parent),b=s.bodies.find(b=>b.id===j.child),gap=N(B(A(V(a.position),mv(matrix(a.rotation),V(j.anchor1))),A(V(b.position),mv(matrix(b.rotation),V(j.anchor2)))));if(gap>plan.limits.anchor_m)return 'anchor_gap:'+j.id;if(j.kind==='revolute'){const rel=qm(cp(qm(a.rotation,j.frame1)),qm(b.rotation,j.frame2)),angle=Math.atan2(Math.sin(2*Math.atan2(rel.x,rel.w)),Math.cos(2*Math.atan2(rel.x,rel.w)));if(Math.max(0,j.limits[0]-angle,angle-j.limits[1])>plan.limits.hinge_limit_violation_rad)return 'hinge_limit:'+j.id;}}if(d.tilt>plan.limits.torso_tilt_rad)return 'torso_domain';if(d.com_drift>plan.limits.com_drift_m)return 'com_drift';for(const id of ['footL','footR'])if(d.foot_drift[id]>plan.limits.foot_drift_m)return 'foot_drift:'+id;if(d.yaw_drift>plan.limits.yaw_drift_rad)return 'yaw_drift';return null;}
export function commandCheck(pre,c,variant){
 keys(c,'phase,cleared,law,applied_torso,applied_pelvis,readback');assert.deepEqual(c.phase,['immutable_PRE','wake_all15','clear_torques','native_pose_commands','compute_from_PRE','add_pair_once','readback_before_step']);const fault=['wrong-sign','missing-reaction'].includes(variant)?variant:null,expected=independentLaw(pre.bodies.find(b=>b.id==='torso'),fault);for(const k of Object.keys(expected)){if(Array.isArray(expected[k]))expected[k].forEach((x,i)=>close(c.law[k][i],x,1e-15));else close(c.law[k],expected[k],1e-15);}keys(c.law,Object.keys(expected).join(','));const a=variant==='off'?[0,0,0]:expected.encoded,b=variant==='off'?[0,0,0]:expected.pelvis;assert.deepEqual(c.applied_torso,a);assert.deepEqual(c.applied_pelvis,b);assert.ok(within(a,plan.controller.cap_Nm)&&within(b,plan.controller.cap_Nm));for(const list of [c.cleared,c.readback]){assert.deepEqual(list.map(x=>x.id),rig.bodies.map(x=>x.id));for(const r of list){keys(r,'id,torque,force');assert.deepEqual(V(r.force),[0,0,0]);const actual=list===c.cleared?[0,0,0]:r.id==='torso'?a:r.id==='pelvis'?b:[0,0,0];assert.deepEqual(V(r.torque),actual);}}const positive=independentLaw(pre.bodies.find(b=>b.id==='torso'));if(fault==='wrong-sign'){assert.ok(D(positive.error,a)<0);assert.notDeepEqual(a,positive.encoded);}if(fault==='missing-reaction'){assert.ok(N(a)>0);assert.deepEqual(b,[0,0,0]);}return fault?'fail_command:'+fault:null;
}

function setupCheck(initial,trial){
 const inertia=spec=>{const m=spec.mass,s=spec.shape;if(s.type==='ball')return [1,1,1].map(()=>.4*m*s.radius**2);if(s.type==='cuboid'){const h=V(s.half);return h.map((_,i)=>m*(h[(i+1)%3]**2+h[(i+2)%3]**2)/3);}const r=s.radius,h=s.half,mc=m*2*h/(2*h+4*r/3),ms=m-mc,t=mc*(r*r/4+h*h/3)+ms*(.4*r*r+h*h+.75*h*r);return [t,.5*mc*r*r+.4*ms*r*r,t];};
 for(const b of initial.bodies){const expected=inertia(rig.bodies.find(x=>x.id===b.id)).sort((a,b)=>a-b),actual=V(b.inertia).sort((a,b)=>a-b);actual.forEach((x,i)=>close(x,expected[i],1e-5));const e=b.world_inverse_inertia;assert.ok(e[0]>0&&e[3]>0&&e[5]>0&&e[0]*e[3]-e[1]*e[1]>0&&e[0]*(e[3]*e[5]-e[4]*e[4])-e[1]*(e[1]*e[5]-e[4]*e[2])+e[2]*(e[1]*e[4]-e[3]*e[2])>0,'positive definite public inverse tensor');}

 const c=plan.cases.find(c=>c.id===trial.case),ax=(a,t)=>({x:a==='X'?Math.sin(t/2):0,y:a==='Y'?Math.sin(t/2):0,z:a==='Z'?Math.sin(t/2):0,w:Math.cos(t/2)}),q=qm(ax('Y',c.yaw),c.axis?ax(c.axis,c.tilt):{x:0,y:0,z:0,w:1}),M=matrix(q),p=plan.initial_pivot_m;
 for(const b of initial.bodies){const s=rig.bodies.find(s=>s.id===b.id),expected=A(p,mv(M,B(V(s.position),p)));V(b.position).forEach((x,i)=>close(x,expected[i],1e-6));assert.ok(qdist(b.rotation,qm(q,s.rotation))<=1e-6);assert.deepEqual(V(b.linear_velocity),[0,0,0]);assert.deepEqual(V(b.angular_velocity),[0,0,0]);assert.deepEqual(V(b.user_torque),[0,0,0]);assert.ok(N(B(V(b.world_com),V(b.position)))<=1e-6);}
 for(const j of initial.joints){assert.ok(j.observation.anchor_error<=1e-6);assert.ok((j.observation.axis_error??0)<=1e-6);assert.ok((j.observation.limit_violation??0)<=1e-6);if(j.kind==='revolute')for(const q of [j.frame1,j.frame2])assert.ok(N(B(mv(matrix(q),[1,0,0]),[1,0,0]))<=1e-6,'authored local hinge +X');}
 if(trial.condition==='free32'){assert.equal(initial.settings.motor_config,null);assert.equal(initial.motor_tracking,null);}else {const m=initial.settings.motor_config;keys(m,'schema_version,controller_id,model,target_convention,stiffness,damping,max_torque_Nm,targets');assert.equal(m.schema_version,1);assert.equal(m.controller_id,'native-pose-hold-force-v1');assert.equal(m.model,'ForceBased');assert.equal(m.target_convention,'moving-frame-v1');assert.equal(m.stiffness,100);assert.equal(m.damping,12);assert.equal(m.max_torque_Nm,20);assert.deepEqual(m.targets,rig.joints.map(j=>({id:j.id,target:j.type==='revolute'?0:{x:0,y:0,z:0,w:1}})));}
}
function immutableAndTracking(s,initial){
 for(let i=0;i<15;i++)for(const k of ['id','body_handle','collider_handle','mass','inertia','principal_frame','shape','ccd','dynamic','additional_solver_iterations','linear_damping','angular_damping','friction','restitution','sensor','native_shape_type','observed_shape','friction_combine','restitution_combine','contact_skin','collision_groups'])assert.deepEqual(s.bodies[i][k],initial.bodies[i][k], 'immutable body '+k);
 for(let i=0;i<14;i++)for(const k of ['id','handle','parent','child','kind','native_type','anchor1','anchor2','frame1','frame2','contacts_enabled','limits'])assert.deepEqual(s.joints[i][k],initial.joints[i][k], 'immutable joint '+k);
 if(initial.settings.motor_config===null){assert.equal(s.motor_tracking,null);return;}
 assert.equal(s.motor_tracking.length,14);for(let i=0;i<14;i++){const t=s.motor_tracking[i],j=s.joints[i],a=s.bodies.find(b=>b.id===j.parent),b=s.bodies.find(b=>b.id===j.child),parent=qm(a.rotation,j.frame1),child=qm(b.rotation,j.frame2),relative=qm(cp(parent),child);keys(t,'joint_id,kind,target,actual,error_rad,relative_angular_velocity_rad_s,limits,configured_axis_cap_Nm');assert.equal(t.joint_id,j.id);assert.equal(t.kind,j.kind);assert.equal(t.configured_axis_cap_Nm,20);assert.deepEqual(t.limits,rig.joints[i].limits);if(j.kind==='revolute'){assert.equal(t.target,0);close(t.actual,j.observation.angle,1e-6);close(t.error_rad,Math.abs(j.observation.angle),1e-6);}else{assert.deepEqual(t.target,{x:0,y:0,z:0,w:1});assert.ok(qdist(t.actual,relative)<1e-6);close(t.error_rad,qdist(t.target,relative),1e-6);}const wr=B(V(b.angular_velocity),V(a.angular_velocity)),wp=mv(matrix(cp(parent)),wr);V(t.relative_angular_velocity_rad_s).forEach((x,k)=>close(x,wp[k],1e-6));}
}

export function worldDecision(run){
 const initial=run.initial;validateState(initial);setupCheck(initial,run.trial);immutableAndTracking(initial,initial);const initialStop=stateStop(initial,initial);if(initialStop)return {kind:'execution_blocker',reason:initialStop,phase:'initial',step:0};if(derived(initial,null).nonfoot.length)return {kind:'execution_blocker',reason:'initial_nonfoot_contact',phase:'initial',step:0};let nofoot=0;
 for(let i=0;i<run.frames.length;i++){const f=run.frames[i];keys(f,'pre,command,command_classification,post,cleared,cpu');assert.equal(f.pre.step,i);assert.equal(f.post.step,i+1);validateState(f.pre);validateState(f.post);immutableAndTracking(f.pre,initial);immutableAndTracking(f.post,initial);for(const b of f.pre.bodies)assert.deepEqual(V(b.user_torque),[0,0,0]);for(const b of f.post.bodies)assert.deepEqual(V(b.user_torque),b.id==='torso'?f.command.applied_torso:b.id==='pelvis'?f.command.applied_pelvis:[0,0,0]);assert.deepEqual(f.pre.settings,initial.settings);assert.deepEqual(f.post.settings,initial.settings);const preStop=stateStop(f.pre,initial);if(preStop)return {kind:'execution_blocker',reason:preStop,phase:'PRE',step:i};assert.equal(f.command_classification,commandCheck(f.pre,f.command,run.trial.variant));assert.deepEqual(f.cleared.map(r=>r.id),rig.bodies.map(b=>b.id),'all15 cleared after POST');for(const r of f.cleared){assert.deepEqual(V(r.torque),[0,0,0]);assert.deepEqual(V(r.force),[0,0,0]);}const d=derived(f.post,initial),stop=stateStop(f.post,initial);if(stop)return {kind:stop.startsWith('outer_state:')?'execution_blocker':'state_terminal',reason:stop,phase:'POST',step:i+1};if(d.nonfoot.length)return {kind:run.trial.condition==='fb32'&&run.trial.variant==='off'?'counterfactual_terminal':'behavior_blocker',reason:'nonfoot_contact',phase:'POST',step:i+1};if(run.trial.condition==='fb32'&&i+1>30){nofoot=d.foot_contact?0:nofoot+1;if(nofoot>=6)return {kind:'behavior_blocker',reason:'foot_contact_loss',phase:'POST',step:i+1};const block=run.frames.slice(30,i+1);if(block.length%60===0||i+1===360){const tail=block.slice(-(block.length%60||60)),loads=tail.map(x=>derived(x.post,initial).loads),means=['footL','footR'].map(id=>loads.reduce((s,x)=>s+x[id],0)/loads.length),total=means[0]+means[1];if(total<plan.limits.total_mean_load_N[0]||total>plan.limits.total_mean_load_N[1]||means.some(x=>x<plan.limits.per_foot_mean_min_N))return {kind:'behavior_blocker',reason:'support_window',phase:'POST',step:i+1};}}
 if(i+1===run.trial.max_steps){if(run.trial.condition==='fb32'&&run.trial.variant==='on'&&(d.tilt>plan.limits.final_torso_tilt_rad||d.transverse_speed>plan.limits.final_transverse_speed_rad_s))return {kind:'behavior_blocker',reason:'terminal_upright',phase:'POST',step:i+1};return {kind:['wrong-sign','missing-reaction'].includes(run.trial.variant)?'expected_negative_detected':'horizon',reason:null,phase:'POST',step:i+1};}}
 return {kind:'incomplete',reason:null,phase:'prefix',step:run.frames.length};
}
function compareRepeat(a,b){if(b.decision.kind!=='incomplete'){assert.equal(a.frames.length,b.frames.length);assert.deepEqual(a.decision,b.decision);}for(let i=0;i<=Math.min(a.frames.length,b.frames.length);i++){const x=i?a.frames[i-1].post:a.initial,y=i?b.frames[i-1].post:b.initial;for(let j=0;j<15;j++){for(const k of ['position','linear_velocity','angular_velocity'])V(x.bodies[j][k]).forEach((v,l)=>close(v,V(y.bodies[j][k])[l],1e-6));assert.ok(qdist(x.bodies[j].rotation,y.bodies[j].rotation)<=1e-6);}assert.deepEqual(x.floor_contacts.map(c=>c.body_id),y.floor_contacts.map(c=>c.body_id));for(let j=0;j<x.floor_contacts.length;j++){V(x.floor_contacts[j].point).forEach((v,l)=>close(v,V(y.floor_contacts[j].point)[l],1e-6));if(i)close(x.floor_contacts[j].normal_load,y.floor_contacts[j].normal_load,1e-5);}}}
// Pair failure is a valid result; technical failures still latch globally.
export function pairAssessment(off,on){
 assert.equal(off.trial.variant,'off');assert.equal(on.trial.variant,'on');
 for(const k of ['condition','case','repeat'])assert.equal(off.trial[k],on.trial[k]);
 const eligible=r=>r.frames.length-(r.decision.kind==='state_terminal'?1:0);
 const n=Math.min(eligible(off),eligible(on));
 if(n<(['pitch','roll'].includes(on.trial.case)?plan.limits.minimum_comparison_steps:1))return {status:'inconclusive',reason:'insufficient_comparison',common_steps:n,rms_off:null,rms_on:null};
 const rms=x=>Math.sqrt(x.frames.slice(0,n).reduce((s,f)=>s+derived(f.post,x.initial).tilt**2,0)/n),a=rms(on),b=rms(off);
 const benefit=['pitch','roll'].includes(on.trial.case)?a<=plan.limits.tilt_pair_rms_ratio*b:a<=b+1e-6&&on.frames.length>=off.frames.length;
 const pass=benefit&&on.decision.kind==='horizon';
 return {status:pass?'pass':'fail',reason:!benefit?'pair_response':on.decision.kind!=='horizon'?on.decision.reason:null,common_steps:n,rms_off:b,rms_on:a};
}
export function prefixDecision(runs,completedCache=null){
 let negative=false,inconclusive=false;
 for(let i=0;i<runs.length;i++){
  const r=runs[i];assert.deepEqual(r.trial,plan.order[i]);
  if(i<runs.length-1)assert.notEqual(r.decision.kind,'incomplete','new world after incomplete prefix');
  const dec=completedCache?.get(r)??worldDecision(r);assert.deepEqual(r.decision,dec);if(completedCache&&dec.kind!=='incomplete')completedCache.set(r,dec);assert.equal(r.frames.length,dec.step,'no state after local terminal');
  if(dec.kind==='execution_blocker')return {...dec,ordinal:i+1,id:r.trial.id};
  if(['behavior_blocker','state_terminal'].includes(dec.kind))negative=true;
  const prev=runs.slice(0,i).find(x=>x.trial.condition===r.trial.condition&&x.trial.case===r.trial.case&&x.trial.variant===r.trial.variant);
  if(prev){try{compareRepeat(prev,r);}catch(e){return {kind:'repeat_blocker',reason:e.message,phase:'prefix',step:dec.step,ordinal:i+1,id:r.trial.id};}}
  if(r.trial.condition==='fb32'&&r.trial.variant==='on'&&dec.kind!=='incomplete'){
   const pair=pairAssessment(runs[i-1],r);negative ||= pair.status==='fail';inconclusive ||= pair.status==='inconclusive';
  }
  for(let repeat=1;repeat<=5;repeat++){
   const pos=runs.find(x=>x.trial.condition==='free32'&&x.trial.case==='pitch'&&x.trial.variant==='on'&&x.trial.repeat===repeat);
   if(!pos||!pos.frames.length)continue;
   for(const variant of ['wrong-sign','missing-reaction']){const neg=runs.find(x=>x.trial.variant===variant&&x.trial.repeat===repeat);assert.ok(neg?.frames.length,'sufficient negative prefix');assert.deepEqual(pos.initial,neg.initial);assert.notDeepEqual(pos.frames[0].command.readback,neg.frames[0].command.readback);}
  }
 }
 return {kind:runs.length===90?(negative?'completed_negative':inconclusive?'completed_inconclusive':'bounded_fullrig_candidate_supported'):'pending',ordinal:runs.length,reason:runs.length===90?(negative?'valid_negative_outcomes':inconclusive?'insufficient_comparison':null):null};
}
export function audit(archive,expectedProvenance){assert.ok(resultValidator(archive),JSON.stringify(resultValidator.errors));keys(archive,'schema_version,namespace,config,provenance,runs,allocation_attempts,public_steps,decision,standing_approval,engine_precision');assert.equal(archive.schema_version,1);assert.equal(archive.namespace,'fullrig-torso-pelvis-ab-v1:'+createHash('sha256').update(fs.readFileSync(new URL('../docs/research/standing-lab/fullrig84/config.json',import.meta.url))).digest('hex'));assert.equal(archive.standing_approval,false);assert.equal(archive.engine_precision,'indeterminate_not_certified');finite(archive);assert.ok(expectedProvenance,'external preregistered provenance required');assert.deepEqual(archive.provenance,expectedProvenance,'preregistered build/source identity');assert.ok(archive.runs.length<=90);assert.equal(archive.allocation_attempts,archive.runs.length);assert.equal(archive.public_steps,archive.runs.reduce((s,r)=>s+r.frames.length,0));assert.ok(archive.public_steps<=14450);for(const r of archive.runs)keys(r,'trial,uuid,initial,frames,decision');const d=prefixDecision(archive.runs);assert.deepEqual(archive.decision,d);if(['execution_blocker','repeat_blocker'].includes(d.kind))assert.equal(d.ordinal,archive.runs.length,'no trailing world after blocker');return {decision:d,attempts:archive.allocation_attempts,steps:archive.public_steps,new_reader_worlds:0};}
