// Research-only adapter; no changes to historical StandingSimulation.
import R from '@dimforge/rapier3d-compat';
import {StandingSimulation,colliderDesc} from '../src/labs/standing/simulation.js';
import {NativePoseHold,neutralMotorConfig} from '../src/labs/standing/motors.js';
import {floorContacts} from '../src/labs/standing/measurement.js';
import {jointObservation} from '../src/labs/standing/math.js';
import {RIG,PLAN,initialBody,law,v,obj} from './fullrig84-model.mjs';
// Copy immediately: Rapier 0.21.0 aliases a shared 16-slot scratch buffer.
// Public symmetric upper triangle, row order; unused slots are not matrix data.
export const inverseInertiaComponents=m=>[m.m11,m.m12,m.m13,m.m22,m.m23,m.m33];
export const init=()=>R.init();
export const version=()=>R.version();
export class StudyWorld {
 constructor(trial){this.trial=trial;this.config=RIG;this.bodies=new Map();this.colliders=new Map();this.joints=new Map();this.world=null;this.events=null;this.motor=null;this.steps=0;}
 allocate(){
  this.world=new R.World(RIG.gravity);this.events=new R.EventQueue(true);this.world.timestep=PLAN.nominal_dt;
  for(const [key,value] of Object.entries(PLAN.solver))if(key!=='additionalSolverIterations')this.world.integrationParameters[key]=value;
  const f=RIG.floor;this.floor=this.world.createCollider(R.ColliderDesc.cuboid(f.half.x,f.half.y,f.half.z).setTranslation(f.position.x,f.position.y,f.position.z).setFriction(f.friction).setRestitution(f.restitution));
  for(const spec of RIG.bodies){const start=initialBody(spec,this.trial.case),p=start.position;const body=this.world.createRigidBody(R.RigidBodyDesc.dynamic().setTranslation(p.x,p.y,p.z).setRotation(start.rotation).setLinearDamping(spec.linearDamping).setAngularDamping(spec.angularDamping));body.setAdditionalSolverIterations(0);const collider=this.world.createCollider(colliderDesc(spec.shape).setMass(spec.mass).setFriction(spec.friction).setRestitution(spec.restitution),body);body.recomputeMassPropertiesFromColliders();const entry={spec,body,collider};this.bodies.set(spec.id,entry);this.colliders.set(collider.handle,entry);}
  for(const spec of RIG.joints){const descriptor=spec.type==='revolute'?R.JointData.revolute(spec.anchorA,spec.anchorB,spec.axis):R.JointData.spherical(spec.anchorA,spec.anchorB);const joint=this.world.createImpulseJoint(descriptor,this.bodies.get(spec.parent).body,this.bodies.get(spec.child).body,true);joint.setContactsEnabled(false);if(spec.limits)joint.setLimits(...spec.limits);this.joints.set(spec.id,{spec,joint,descriptor});}
  StandingSimulation.prototype.auditRig.call(this);
  if(this.trial.condition==='fb32'){this.motor=new NativePoseHold(neutralMotorConfig(RIG),RIG);this.motor.bind(this);}
 }
 settings(){const ip=this.world.integrationParameters;return {floor:{parent:this.floor.parent()?.handle??null,native_shape_type:this.floor.shapeType(),position:{...this.floor.translation()},rotation:{...this.floor.rotation()},half:{...this.floor.halfExtents()},friction:this.floor.friction(),restitution:this.floor.restitution(),friction_combine:this.floor.frictionCombineRule(),restitution_combine:this.floor.restitutionCombineRule(),contact_skin:this.floor.contactSkin(),sensor:this.floor.isSensor(),collision_groups:this.floor.collisionGroups()},dt:this.world.timestep,gravity:{...this.world.gravity},solver:Object.fromEntries(Object.keys(PLAN.solver).filter(k=>k!=='additionalSolverIterations').map(k=>[k,ip[k]])),counts:{bodies:this.world.bodies.len(),colliders:this.world.colliders.len(),joints:this.world.impulseJoints.len()},motor_config:this.motor?structuredClone(this.motor.config):null};}
 snapshot(initial=false){
  const bodies=[...this.bodies.values()].map(({spec,body,collider})=>({id:spec.id,body_handle:body.handle,collider_handle:collider.handle,position:{...body.translation()},rotation:{...body.rotation()},linear_velocity:{...body.linvel()},angular_velocity:{...body.angvel()},mass:body.mass(),world_com:{...body.worldCom()},inertia:{...body.principalInertia()},principal_frame:{...body.principalInertiaLocalFrame()},world_inverse_inertia:inverseInertiaComponents(body.effectiveWorldInvInertia()),sleeping:body.isSleeping(),dynamic:body.isDynamic(),ccd:body.isCcdEnabled(),additional_solver_iterations:body.additionalSolverIterations(),linear_damping:body.linearDamping(),angular_damping:body.angularDamping(),user_torque:{...body.userTorque()},user_force:{...body.userForce()},collider_position:{...collider.translation()},collider_rotation:{...collider.rotation()},friction:collider.friction(),restitution:collider.restitution(),sensor:collider.isSensor(),native_shape_type:collider.shapeType(),observed_shape:spec.shape.type==='ball'?{type:'ball',radius:collider.radius()}:spec.shape.type==='capsule'?{type:'capsule',half:collider.halfHeight(),radius:collider.radius()}:{type:'cuboid',half:{...collider.halfExtents()}},friction_combine:collider.frictionCombineRule(),restitution_combine:collider.restitutionCombineRule(),contact_skin:collider.contactSkin(),collision_groups:collider.collisionGroups(),shape:structuredClone(spec.shape)}));
  const joints=[...this.joints.values()].map(e=>({id:e.spec.id,parent:e.spec.parent,child:e.spec.child,kind:e.spec.type,handle:e.joint.handle,native_type:e.joint.type(),anchor1:{...e.joint.anchor1()},anchor2:{...e.joint.anchor2()},frame1:{...e.joint.frameX1()},frame2:{...e.joint.frameX2()},contacts_enabled:e.joint.contactsEnabled(),limits:e.spec.type==='revolute'?[e.joint.limitsMin(),e.joint.limitsMax()]:null,observation:jointObservation(e)}));
  const self_contacts=[];const es=[...this.bodies.values()];for(let i=0;i<es.length;i++)for(let j=i+1;j<es.length;j++){const a=es[i],b=es[j];if(initial){const c=a.collider.contactCollider(b.collider,0);if(c&&c.distance<=0)self_contacts.push({a:a.spec.id,b:b.spec.id,distance:c.distance,point1:{...c.point1},point2:{...c.point2},normal:{...c.normal1},impulse:null});}else this.world.contactPair(a.collider,b.collider,(m,flipped)=>{for(let k=0;k<m.numContacts();k++)if(m.contactDist(k)<=0)self_contacts.push({a:a.spec.id,b:b.spec.id,distance:m.contactDist(k),point1:{...m.localContactPoint1(k)},point2:{...m.localContactPoint2(k)},normal:{...m.normal()},impulse:m.contactImpulse(k),flipped});});}

  const floor_manifolds=[];if(!initial)for(const {spec,collider} of this.bodies.values())this.world.contactPair(this.floor,collider,(m,flipped)=>{floor_manifolds.push({body_id:spec.id,flipped,normal:{...m.normal()},contacts:Array.from({length:m.numContacts()},(_,i)=>({distance:m.contactDist(i),local1:{...m.localContactPoint1(i)},local2:{...m.localContactPoint2(i)},impulse:m.contactImpulse(i)}))});});

  return {step:this.steps,observed_time:this.steps*PLAN.nominal_dt,settings:this.settings(),bodies,joints,floor_contacts:floorContacts(this.world,this.floor,es,initial),self_contacts,floor_manifolds,motor_tracking:this.motor?this.motor.tracking():null,native_effort:null,native_effort_reason:'Supported API cannot separate native motor/contact/limit solver impulses',cpu_ms:null};
 }
 clear(){for(const {body}of this.bodies.values())body.resetTorques(true);return this.readback();}
 readback(){return [...this.bodies.values()].map(({spec,body})=>({id:spec.id,torque:{...body.userTorque()},force:{...body.userForce()}}));}
 prepare(pre){for(const {body}of this.bodies.values())body.wakeUp();const cleared=this.clear();this.motor?.command();const b=pre.bodies.find(b=>b.id==='torso'),fault=['wrong-sign','missing-reaction'].includes(this.trial.variant)?this.trial.variant:null,command=law(b.rotation,v(b.angular_velocity),fault),torso=this.trial.variant==='off'?[0,0,0]:command.encoded,pelvis=this.trial.variant==='off'?[0,0,0]:command.pelvis;this.bodies.get('torso').body.addTorque(obj(torso),true);this.bodies.get('pelvis').body.addTorque(obj(pelvis),true);return {phase:['immutable_PRE','wake_all15','clear_torques','native_pose_commands','compute_from_PRE','add_pair_once','readback_before_step'],cleared,law:command,applied_torso:torso,applied_pelvis:pelvis,readback:this.readback()};}
 step(){const t=performance.now();this.world.step(this.events);const cpu=performance.now()-t;this.steps++;this.events.drainCollisionEvents(()=>{});this.events.drainContactForceEvents(()=>{});return cpu;}
 dispose(){this.motor?.clear();this.events?.free();this.world?.free();this.events=null;this.world=null;}
}
